apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
spec:
  replicas: 2
  selector:
    matchLabels:
      name: httpd-deployment
  template:
    metadata:
      labels:
        name: httpd-deployment
    spec:
      containers:
        - name: httpd-deployment
          image: k8sdemoregistory.azurecr.io/kcsakashpreethttpd::#{tag}#
          imagePullPolicy: Always
          name: httpd-deployment
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-deployment
spec:
  ports:
  - protocol: TCP  
    port: 80
    targetPort: 80
  selector:
    name: httpd-deployment
  type: LoadBalancer
