apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd-deployment  
  template:
    metadata:
      labels:
        app: httpd-deployment
    spec:
      containers:
        - name: httpd
          image: k8sdemoregistory.azurecr.io/kcsakashpreethttpd:#{tag}#
          imagePullPolicy: Always
          name: httpd-deployment
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: httpd-deployment
  type: LoadBalancer
