apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: httpd-deployment 
    spec:
      containers:
      - name: httpd
        image: tsttst.azurecr.io/httpd
        ports:
        - containerPort: 80
