apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: httpd-deployment 
    spec:
      containers:
      - name: httpd
        image: k8sdemoregistory.azurecr.io/kcsakashpreethttpd:httpd
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
  #selector:
    #run: httpd-deployment
  selector:
    app: httpd-deployment
  selector:
    app: httpd-deployment
  type: LoadBalancer
